# Generated by Django 4.2.1 on 2023-05-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1998-12-14'),
            preserve_default=False,
        ),
    ]
